name: Action

on:
  pull_request: {}
  push: { branches: [master] }
  
jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-builder@v2
        name: Unity Builder
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
      - uses: actions/upload-artifact@v2
        with:
          name: Unity Builder
          path: build
          retention-days: 90
